services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev
    depends_on:
      - backend
      - frontend
#      - merch

#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    environment:
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
#    depends_on:
#      - zookeeper
#    networks:
#      - dev
#
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    networks:
#      - dev

#  merch:
#    build:
#      context: ./merch
#      dockerfile:  Dockerfile
#    ports:
#      - "8081:8081"
#    #restart: always
#    networks:
#      - dev
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db_merch:5432/merchdb
#      SPRING_DATASOURCE_USERNAME: merchuser
#      SPRING_DATASOURCE_PASSWORD: merch123
#    depends_on:
#     - db_merch

  backend:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #restart: always
    networks:
      - dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_auth:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: auth123
    depends_on:
      - db_auth

  frontend:
    build:
      context: ./frontend_my_bank
      dockerfile: Dockerfile
    ports:
      - "3000:80"
   # restart: always
    depends_on:
      - backend
    networks:
      - dev

  db_auth:
    image: postgres:latest
    ports:
      - "5432:5432"
   # restart: always
    networks:
      - dev
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: auth123
    volumes:
      - db_auth:/var/lib/postgresql/data

#  db_merch:
#    image: postgres:latest
#    ports:
#      - "5433:5432"
#    # restart: always
#    networks:
#      - dev
#    environment:
#      POSTGRES_DB: merchdb
#      POSTGRES_USER: merchuser
#      POSTGRES_PASSWORD: merch123
#    volumes:
#      - db_auth:/var/lib/postgresql/data

volumes:
  db_auth:
#  db_merch:

networks:
  dev: