spring.application.name=authservice
server.port=8080


# Kafka configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# DB configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=authuser
spring.datasource.password=auth123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT configuration
jwt.secret.public.access=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJ1wE1C3Vp4KoHfrzA1QU1MWA+1OA/fioKKA244UMNF+FNwxIdOxd9eadb1VK5VcW9jF/algmYNErh8BjXEEtlf8B7lXSfDJ5PkSDKBMaSC7bq6hu7APPHVKT/uvD/234jemk2r4UUZH17fzE28WiCCoUYj7dSYdYXaqbOpMy2nZVcTitCdOH9cg4P+tLpWdrOHhRIPpFSqUiCcjIm9dBymgAOIiFeTAZJ0huc+Y6xR3+HLerDeW+G8PtuBm8GNyPJGJkoonMYG7UwD3xJb8kHSYVKiFizAGZdg6N1iumLzxFErchx44HllbX7nZKOtLAUi2CIgRn/LcWLQib74OBQIDAQAB
jwt.secret.private.access=MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC0nXATULdWngqgd+vMDVBTUxYD7U4D9+KgooDbjhQw0X4U3DEh07F315p1vVUrlVxb2MX9qWCZg0SuHwGNcQS2V/wHuVdJ8Mnk+RIMoExpILturqG7sA88dUpP+68P/bfiN6aTavhRRkfXt/MTbxaIIKhRiPt1Jh1hdqps6kzLadlVxOK0J04f1yDg/60ulZ2s4eFEg+kVKpSIJyMib10HKaAA4iIV5MBknSG5z5jrFHf4ct6sN5b4bw+24GbwY3I8kYmSiicxgbtTAPfElvyQdJhUqIWLMAZl2Do3WK6YvPEUStyHHjgeWVtfudko60sBSLYIiBGf8txYtCJvvg4FAgMBAAECggEABF227xyZJfyhjKIBfvgGbFE6m8MxitqD7ban70bGuaxixB3TiToNFPTPDNAUHj7Y0faSSLC+v09DSoNA3hqwjrjfRI+IKucpdkHIHCqG1la+eS07Bya5I5DBSGAw6e3L82m9etxP3uUYSQBvHZXmoUlK0FfDnmAavzenZIUgcJ1Wv7b4P74usWJleVPItTVKrlt3sApkytSWruy0Ugm6IzLefezQOuY1/c5F37EDsHbWCmxx0OXEk6LvzdnLkbBuWNDgZ6vL9OjBKnMzo5eaeLe72I3F6EKBMa7efgfhyxwudSW27QHVJkQnRp9QjWHcqsWwNIZxa+IJnNsV45Rm8QKBgQDpNE8HxQp3uzaLx5Pw+q0iU8OtTnlFGv0GCgj4SyiWrWdh6y2WfNvmIx3aN4TejkYyWNjgsxVwp8Um1elJgRxTLZYF7GKLHuNepJU0DPSz7vmn5wOuXiExesf5UY6lDmp9swH/rmDNSRtYbuu/779dtOnpBnDfLcnEFVKAM7zqMQKBgQDGRSL3Do2ZBKsb1GubuWwn3MpUhTKe7oWzvLZD7dnf7zBLnGHTgvyrja9S03gIdGTVUP1z62J3h6SL4JXuX7mFjEKJvcuQKZxzg2s5lzIhJpkGcF8pLY6TmvHYm2WjF9bSqlYPlzaqcX3p7ioi973BKZImX6sFTzkiIzFb/x5YFQKBgQDBNyi/nD7XAtLnrxzhDSDDjzlR7vHFEt5O0aOq7MKdTOCaHXtw8tRS8gd61IMOzjxU3I4cZeQ+qZJMYfFeiE2KkPt6vubKs3XY5W4FaTKZnkdVGK9RGgZQc5UZ+bvA/5e1u8nNKJJlo8u3UnebWC1qm0kuW7rK/qnr/2qSc8tzEQKBgQC/GmRZPO2+T4GdkWEm99IHmghq7vebuMumMn57ewZFkYY7Wr/v3pEryaTzcGCBxa5q7WVeFcMS8urm59GbsShgUJDRst5CVdk2fbUcDV+EFG/qhOU0C3UhUHdLEH0mdhPZedT5sgY+wqValPSIP8HmLOtxkUSGGZY4ETPCOGRHAQKBgQC5wTtITLpwCy+M2SvTFBlrq4Nsdy9lMxgsllPwzozjeye0nzBwnAhpTNWLhRE99e38E+xbulTdiNrFgwu8+zEC+a0h7XLLhuwxU+kLi/x2HMaJoH1NnUx8130Y3Xz1A3Py9ISmrNk93Kv1o6XRDrwwwJVhkArBNfF4pFkpaQjtXQ==
jwt.secret.public.refresh=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsn/2tTIwizhhS9B/N7pVlQ/dOZ2QwwDDUTrGyC0fOoYTNqfpRn+U6xik6MP4YeO/ynYvATCdph9iEM18WnNt8OET3Ek2VSbDLG2NMHUfYO3DXzn0SS6TSBKf28+sGxR+dC6zfrVeA4ezXqQ7MrQg3kS6UcqtEJj3lSpx/Zlto4e8mNlJlOO36Kqy/z/ARK0Sc1soVivCJkDV7juPiGpX+xokLQig1iUiG/TOMH/TuGsUHof4A83DX99UXK903zHHwlvgjXYeOgSE6NMVKceAb/8+L/nCGY8d7D2t/Zyk+rGQuKaLNwp6vXvCVO60ucMiqdRtzwcZatU64WFHXoEIXwIDAQAB
jwt.secret.private.refresh=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyf/a1MjCLOGFL0H83ulWVD905nZDDAMNROsbILR86hhM2p+lGf5TrGKTow/hh47/Kdi8BMJ2mH2IQzXxac23w4RPcSTZVJsMsbY0wdR9g7cNfOfRJLpNIEp/bz6wbFH50LrN+tV4Dh7NepDsytCDeRLpRyq0QmPeVKnH9mW2jh7yY2UmU47foqrL/P8BErRJzWyhWK8ImQNXuO4+Ialf7GiQtCKDWJSIb9M4wf9O4axQeh/gDzcNf31Rcr3TfMcfCW+CNdh46BITo0xUpx4Bv/z4v+cIZjx3sPa39nKT6sZC4pos3Cnq9e8JU7rS5wyKp1G3PBxlq1TrhYUdegQhfAgMBAAECggEAEXUNYkw9zifd8CW8g21AWHs8NhnQYhntgEDA1yv+jWE2eNZ0LJZmsJVw72jXHm/BPqJPV4zzJh+UnjMSkeAPJQtGP3mTjEFlvi8aq14RCxBF1sbautuIwPg9VSia2u0mruMwX9iKEMtRQhTKy1stib9r/3rUcTacpCSKEHTUcbU3PMA2uHU7ILKqYRrQ73m7PzNtMQljAsby7vYGhqIEml+LOnFj7+wqxZ4TsNoDXYLy3F7L3GIjOkF8K9HFTqnOjHkkKVt+VhFtoxtkbTITONYgZarn0aPZKjqeun2M5Zm3Z2cd1siYi2FdR8Vj1NP+NNRzZ7VQJXB9SAJt4PS69QKBgQDrg+hPx+JHpKLde35VupCbzHC42yAjYEUM0ssaBngw6Pfnj1Nw4tYRVt54z60aOV+alpiisDmQxLMXFoO/s+RXvfGVcpepEuUFlF0eXW0QDOE69WQL6ZZMuZlVIBYbRDaZ4WyxNWnZbpZ17UnNfkvyjwFHr7e6iqiHOI8umWfibQKBgQDCBoZQtHbH6yF+LGrX01sU5lrLAZo/IPhXnoa/F4/jmGiWml4zgzsltRjWY7sNEjvZGKx7uOiWhaf/oigRajRdxeuds9DUgkHWlDmXotCbXe5Vg9Lw+nHYZ26mBsDQ4ZJjp4k0QaKS+G19aB3cD2XkZ3wWuAO/qXNO45riGH12ewKBgQCMe14zWJONEJNlcahmEqb3h/clDPAaqe4GPCaSG5HN+ukE4uVuzJ/ML/j8L0SeA+MXHwVk5aEwzWPWPcPQscle3Rohfv0gCPk7Xsg8uJW5oTUoKf/Ha0oP8hWYRU9qbEH1gBWJjsbYv7JYHXaMcO10fgDRdesuBk+IeSBPN4pT8QKBgDh4MatXeqKg2nSgdNAv4Xhpus8OvlfVPrIxn0IKl4REHVyHvRb9AL/uvzXWfOBHCEgdGEZCAN+eMtEB3uuCn48TRYn2hbbz2jmblk99wX0Wj4EwBrrACVZUdC26FXA11qdOYW5mE+z2hNdU8CvWB2+8dq8eC2lC5h51u+RGAG31AoGAcX2QJrFaRLRgS6vwnPaUa38ONjS2Mfri5YcunYJTd+axpIKXRlfUdZGavtXLup1Pt6qoN2lCW8CHW6xSF2tARd4PWThqb9ttBQIoEe0j59Ut2FSfZ42uCNZrHZc4WtzCpJwBrRHLFUl8OMyZLMcJ39gyqsZo9IJlFY+tbcct604=


# GitHub configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liuVPT0C2whvQmZj
spring.security.oauth2.client.registration.github.client-secret=1cd47bcfa9da577192763dc078b5296f652e8a38
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id

logging.level.org.springframework.security=DEBUG


# Google configuration
spring.security.oauth2.client.registration.google.client-id=924612665052-apjpos9cmml0nln77kjd0ou56m8pqpec.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid, profile, email, name
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


# Facebook configuration (VPN!)
spring.security.oauth2.client.registration.facebook.client-id=YOUR_APP_ID
spring.security.oauth2.client.registration.facebook.client-secret=YOUR_APP_SECRET
spring.security.oauth2.client.registration.facebook.scope=public_profile, email
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v10.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v10.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email
spring.security.oauth2.client.provider.facebook.user-name-attribute=id



